# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='LastState',
            field=models.TextField(default=[123, 234234234, 345345345]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Objs',
            field=models.TextField(default=[123, 234234234, 345345345]),
            preserve_default=False,
        ),
    ]
